sonar.projectKey=sap-cc-static-code-analysis
sonar.projectName=sap-commerce-static-code-analysis
sonar.host.url=http://192.168.8.200:9000
sonar.token=sqp_6cbd0de37d34ebc6772d8d0acb0fd7245e600689
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.java.binaries=build/classes/kotlin/main
sonar.java.test.binaries=build/classes/kotlin/test
sonar.junit.reportPaths=build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
