package com.cci.sapcclint.rules

object DefaultTypeSystemRules {
    fun all(): List<TypeSystemRule> = listOf(
        TSEnumValueMustBeUppercaseRule(),
        TSTypeNameMustStartWithUppercaseLetterRule(),
        TSQualifierMustStartWithLowercaseLetterRule(),
        TSTypeNameMustNotStartWithGeneratedRule(),
        TSTypeNameMustPointToExistingTypeRule(),
        TSDeploymentTableMustExistForItemExtendingGenericItemRule(),
        TSNoDeploymentTableShouldExistForItemIfNotExtendingGenericItemRule(),
        TSMandatoryFieldMustHaveInitialValueRule(),
        TSImmutableFieldMustHaveInitialValueRule(),
        TSUseOfUnoptimizedAttributesIsNotRecommendedRule(),
        TSCollectionsAreOnlyForDynamicAndJaloRule(),
        TSJaloPersistanceTypeIsDeprecatedRule(),
        TSCmpPersistanceTypeIsDeprecatedRule(),
        TSJaloClassIsNotAllowedWhenAddingFieldsToExistingClassRule(),
        TSAttributeHandlerMustBeSetForDynamicAttributeRule(),
        TSDefaultValueForEnumTypeMustBeAssignableRule(),
        TSItemMetaTypeNameMustPointToValidMetaTypeRule(),
        TSItemAttributeMetaTypeNameMustPointToValidMetaTypeRule(),
        TSRelationElementMetaTypeNameMustPointToValidMetaTypeRule(),
        TSCatalogAwareCatalogVersionAttributeQualifierRule(),
        TSCatalogAwareUniqueKeyAttributeQualifierRule(),
        TSDeploymentTableMustBeUniqueRule(),
        TSDeploymentTypeCodeMustBeUniqueRule(),
        TSDeploymentTableMustExistForManyToManyRelationRule(),
        TSDeploymentTagMustNotBeDeclaredForO2MRelationRule(),
        TSDeploymentTableMustNotBeRedeclaredInChildTypesRule(),
        TSDeploymentTableNameLengthShouldBeValidRule(),
        TSDeploymentTypeCodeMustBeGreaterThanTenThousandRule(),
        TSDeploymentTypeCodesMustBeGreaterThanTenThousandForRelationsRule(),
        TSDeploymentTypeCodeReservedForB2BCommerceExtensionRule(),
        TSDeploymentTypeCodeReservedForCommonsExtensionRule(),
        TSDeploymentTypeCodeReservedForLegacyXPrintExtensionRule(),
        TSDeploymentTypeCodeReservedForPrintExtensionRule(),
        TSDeploymentTypeCodeReservedForProcessingExtensionRule(),
        TSDeploymentTypeCodeReservedInspectionRule(),
        TSOnlyOneSideN2mRelationMustBeNotNavigableRule(),
        TSQualifierAndModifiersMustNotBeDeclaredForNavigableFalseRule(),
        TSQualifierMustExistForNavigablePartInN2MRelationRule(),
        TSOrderingOfRelationShouldBeAvoidedRule(),
        TSListsInRelationShouldBeAvoidedRule(),
    )
}
